### PR TITLE
Add custom Dropbox Service Provider handler

### PR DESCRIPTION
**Pull request by timheap**
Based on information in #10 from @fedecastelli. Could you try this fork out, using the DropboxSPHandler instead of your modifications? Without a Dropbox Business account, I have no way of verifying if this works.

Dropbox uses sha256 and does not support sha1. It also requires dates to be formatted a particular way. The DropboxSPHandler handles these quirks. Additional methods were added to the IdentityProvider and SPHandler classes to support these new requirements.

### CODE REVIEW

**Comment by fedecastelli** [comment]
I tested your fork out and I used DropboxSPHandler instead of my modifications. I had to make three quick changes because it wasn't working.
The first one is: I had to create the class `RsaSha256Signer` in `signing.py` file because it's not supported also the `rsa-sha1` algorithm. This is the class I had to create:

```python
class RsaSha256Signer(Signer):
    uri = 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'

    def __init__(self, key: Union[X509, PKey]):
        self.key = key

    def __call__(self, data: bytes):
        data = OpenSSL.crypto.sign(self.key, data, "sha256")
        return base64.b64encode(data).decode('ascii')
```

The second one: I had to override the method `get_sp_signer` in the `DropboxSPHandler` class. This is the method I wrote:

```python
def get_sp_signer(self):
    private_key = self.idp.get_idp_private_key()
    return RsaSha256Signer(private_key)
```

The third one: I had to override the method `validate_request` in the `DropboxSPHandler` class. I don't know why, but Dropbox doesn't set the destination in the SAMLRequest and the standard method was raising an error. This is the method I wrote:

```python
def validate_request(self, request: AuthnRequestParser):
    """
    Validates the SAML request against the configuration of this Service
    Provider handler . Sub-classes should override this and raise a
    `CannotHandleAssertion` exception if the validation fails.

    Raises:
        CannotHandleAssertion: if the ACS URL specified in the SAML request
            doesn't match the one specified in the SP handler config.
    """
    if self.entity_id != request.issuer:
        raise CannotHandleAssertion(
            f'EntityID mismatch {self.entity_id} != {request.issuer}')

    if self.acs_url != request.acs_url:
        raise CannotHandleAssertion(
            f'ACS URL mismatch {self.acs_url} != {request.acs_url}')
```

**Comment by timheap** [comment]
@fedecastelli I pushed another commit incorporating your extra changes. Can you please test this again?

**Comment by timheap** [comment]
Updated again, based on your new information. Setting the attribute to the empty string - as opposed to not setting the attribute - seems to go against the SAML spec. I've handled this bad behaviour directly in the DropboxSPHandler, so other Service Providers will still have the stricter validation that does not allow for empty strings.

**Comment by fedecastelli** [comment]
Now it's working perfectly! For me, you can merge it in the `master` branch. I know that setting the attribute to an empty string goes against the SAML spec but unfortunately it's what Dropbox is doing.

Thank you for what you did! :)

**Comment by timheap** [comment]
Merged, and released as part of 0.3.0. Thanks for your help in getting this working!

I plan on adding tests later, but it was simply not going to happen at this time of year. For now, this component is not part of the automated testing, so please feel free to report any issues you encounter if something breaks.

**Pull request merged**
